kind: Namespace
apiVersion: v1
metadata:
  name: patch-operator

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: patch-operator-operator-group
  namespace: patch-operator
spec:
  targetNamespaces: []

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: patch-operator-subscription
  namespace: patch-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: patch-operator
  source: community-operators
  sourceNamespace: openshift-marketplace