apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-operator-application
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/ocp-gitops/gitops-cluster.git'
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true