apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-kafka-application
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/ocp-gitops/amq-streams-example.git'
    targetRevision: main
    path: example-kafka/overlays/default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: example-kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true