apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sso-application
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/ocp-gitops/gitops-sso.git'
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sso
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true